/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum02072026;

import javax.swing.JOptionPane;

/**
 *
 * @author alyas
 */
public class MenuUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        txtTotal.setEditable(false);
        txtMakanan.setEditable(false);
        txtMinuman.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        lblMeja = new javax.swing.JLabel();
        txtMeja = new javax.swing.JTextField();
        btnMakanan = new javax.swing.JButton();
        btnMinuman = new javax.swing.JButton();
        lblMakanan = new javax.swing.JLabel();
        lblMinuman = new javax.swing.JLabel();
        txtMakanan = new javax.swing.JTextField();
        txtMinuman = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudul.setText("FORM PEMESANAN KAFE ABC");

        lblNama.setText("Nama Pelanggan");

        lblMeja.setText("Nomor Meja");

        btnMakanan.setText("MENU MAKANAN");
        btnMakanan.addActionListener(this::btnMakananActionPerformed);

        btnMinuman.setText("MENU MINUMAN");
        btnMinuman.addActionListener(this::btnMinumanActionPerformed);

        lblMakanan.setText("Total Harga Makanan");

        lblMinuman.setText("Total Harga Minuman");

        txtMakanan.setText("0");

        txtMinuman.setText("0");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        lblTotal.setText("Total Harga");

        txtTotal.setText("0");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(this::btnSelesaiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMakanan)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMeja)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNama)
                                    .addGap(54, 54, 54)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnMinuman))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHitung)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMakanan)
                                    .addComponent(lblMinuman))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotal)
                                .addGap(50, 50, 50)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lblJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btnReset)
                        .addGap(101, 101, 101)
                        .addComponent(btnKeluar)
                        .addGap(116, 116, 116)
                        .addComponent(btnSelesai)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblJudul)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMakanan)
                        .addComponent(txtMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeja)
                    .addComponent(txtMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinuman)
                    .addComponent(txtMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnMakanan))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar)
                    .addComponent(btnSelesai))
                .addGap(41, 41, 41))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakananActionPerformed
        MenuMakanan frm = new MenuMakanan(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMakananActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        if(txtNama.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Nama Tidak Boleh Kosong");
            txtNama.requestFocus();
        }else if(txtMeja.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Nomor meja harus diisi");
            txtMeja.requestFocus();
        }
            
        double mkn = Double.parseDouble(txtMakanan.getText());
        double min = Double.parseDouble(txtMinuman.getText());
        double tot = mkn+min;
        txtTotal.setText(Double.toString(tot));
        
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        JOptionPane.showMessageDialog(this,"Pesanan atas nama"+txtNama.getText()+
                "\nNomor Meja"+txtMeja.getText()+"\nSudah Selesai");
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
         int pil = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar?","Konfirmasi Keluar",JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(pil==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinumanActionPerformed
      MenuMinuman frm = new MenuMinuman(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMinumanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      txtNama.setText("0");
      txtMeja.setText("0");
      txtTotal.setText("0");
      txtMakanan.setText("0");
      txtMinuman.setText("0");
      
    }//GEN-LAST:event_btnResetActionPerformed

    
    public void setTotalMakanan(String nilai){
        txtMakanan.setText(nilai);
    
    }
    public void setTotalMinuman(String nilai){
        txtMinuman.setText(nilai);
    }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMakanan;
    private javax.swing.JButton btnMinuman;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblMakanan;
    private javax.swing.JLabel lblMeja;
    private javax.swing.JLabel lblMinuman;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtMakanan;
    private javax.swing.JTextField txtMeja;
    private javax.swing.JTextField txtMinuman;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
