/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum02072026;

/**
 *
 * @author alyas
 */
public class MenuMinuman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMinuman.class.getName());

    /**
     * Creates new form MenuMinuman
     */
    public MenuMinuman() {
        initComponents();
        txtEsteh.setEditable(false);
        txtJus.setEditable(false);
        txtMineral.setEditable(false);
        txtTotal.setEditable(false);
      
    }
    
    private MenuUtama utama;
    public MenuMinuman(MenuUtama utama) {
        this.utama = utama;
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        txtEsteh = new javax.swing.JTextField();
        txtJus = new javax.swing.JTextField();
        txtMineral = new javax.swing.JTextField();
        chkEsteh = new javax.swing.JCheckBox();
        chkJus = new javax.swing.JCheckBox();
        chkMineral = new javax.swing.JCheckBox();
        cbEsteh = new javax.swing.JComboBox<>();
        cbJus = new javax.swing.JComboBox<>();
        cbMineral = new javax.swing.JComboBox<>();
        txtTotalEsteh = new javax.swing.JTextField();
        txtTotalJus = new javax.swing.JTextField();
        txtTotalMineral = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setText("FORM MENU MINUMAN");

        txtEsteh.setText("0");
        txtEsteh.addActionListener(this::txtEstehActionPerformed);

        txtJus.setText("0");
        txtJus.addActionListener(this::txtJusActionPerformed);

        txtMineral.setText("0");

        chkEsteh.setText("Es Teh");
        chkEsteh.addActionListener(this::chkEstehActionPerformed);

        chkJus.setText("Jus Mangga");
        chkJus.addActionListener(this::chkJusActionPerformed);

        chkMineral.setText("Mineral");
        chkMineral.addActionListener(this::chkMineralActionPerformed);

        cbEsteh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbEsteh.addActionListener(this::cbEstehActionPerformed);

        cbJus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJus.addActionListener(this::cbJusActionPerformed);

        cbMineral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMineral.addActionListener(this::cbMineralActionPerformed);

        txtTotalEsteh.setText("0");
        txtTotalEsteh.addActionListener(this::txtTotalEstehActionPerformed);

        txtTotalJus.setText("0");
        txtTotalJus.addActionListener(this::txtTotalJusActionPerformed);

        txtTotalMineral.setText("0");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        btnTotal.setText("Total");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        txtTotal.setText("0");
        txtTotal.addActionListener(this::txtTotalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTotal)
                .addGap(47, 47, 47)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkMineral, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chkJus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEsteh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMineral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTotalMineral, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTotalJus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(txtTotalEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnKembali)
                                    .addComponent(lblJudul)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnReset)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblJudul)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEsteh)
                            .addComponent(txtEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkJus)
                            .addComponent(txtJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalJus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkMineral)
                            .addComponent(txtMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJusActionPerformed

    private void txtTotalJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalJusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalJusActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void chkEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstehActionPerformed
        txtEsteh.setText("7000");
    }//GEN-LAST:event_chkEstehActionPerformed

    private void chkJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJusActionPerformed
        txtJus.setText("15000");
    }//GEN-LAST:event_chkJusActionPerformed

    private void chkMineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMineralActionPerformed
        txtMineral.setText("5000");
    }//GEN-LAST:event_chkMineralActionPerformed

    private void cbEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstehActionPerformed
        int jumlah = (int)cbEsteh.getSelectedIndex();
        double harga = Double.parseDouble(txtEsteh.getText());
        double total = jumlah*harga;
        txtTotalEsteh.setText(Double.toString(total));
    }//GEN-LAST:event_cbEstehActionPerformed

    private void cbJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJusActionPerformed
        int jumlah = (int)cbJus.getSelectedIndex();
        double harga = Double.parseDouble(txtJus.getText());
        double total = jumlah*harga;
        txtTotalJus.setText(Double.toString(total));
    }//GEN-LAST:event_cbJusActionPerformed

    private void cbMineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMineralActionPerformed
        int jumlah = (int)cbMineral.getSelectedIndex();
        double harga = Double.parseDouble(txtMineral.getText());
        double total = jumlah*harga;
        txtTotalMineral.setText(Double.toString(total));
    }//GEN-LAST:event_cbMineralActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double esteh = Double.parseDouble(txtTotalEsteh.getText());
        double jus = Double.parseDouble(txtTotalJus.getText());
        double mineral = Double.parseDouble(txtTotalMineral.getText());
        double total = esteh+jus+mineral;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMinuman(total);
        this.dispose();
        
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtEsteh.setText("0");
        txtJus.setText("0");
        txtMineral.setText("0");
        txtTotalEsteh.setText("0");
        txtTotalJus.setText("0");
        txtTotalMineral.setText("0");
        txtTotal.setText("0");
        cbEsteh.setSelectedIndex(0);
        cbJus.setSelectedIndex(0);
        cbMineral.setSelectedIndex(0);
        chkEsteh.setSelected(false);
        chkJus.setSelected(false);
        chkMineral.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstehActionPerformed

    private void txtTotalEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalEstehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalEstehActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMinuman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbEsteh;
    private javax.swing.JComboBox<String> cbJus;
    private javax.swing.JComboBox<String> cbMineral;
    private javax.swing.JCheckBox chkEsteh;
    private javax.swing.JCheckBox chkJus;
    private javax.swing.JCheckBox chkMineral;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField txtEsteh;
    private javax.swing.JTextField txtJus;
    private javax.swing.JTextField txtMineral;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalEsteh;
    private javax.swing.JTextField txtTotalJus;
    private javax.swing.JTextField txtTotalMineral;
    // End of variables declaration//GEN-END:variables
}
